---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka-consumer
  labels:
    app: kafka-consumer

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kafka-consumer
  name: kafka-consumer
  labels:
    app: kafka-consumer
# Replica set
spec:
  revisionHistoryLimit: 5
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
# Pods
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: registry.hub.docker.com/josegrelnx/kafka_consumer:latest
        ports:
          - containerPort: 8082
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 500Mi
            cpu: 500m
        env:
        - name: INPUT_TOPIC
          value: "input"
        - name: OUTPUT_TOPIC
          value: "output"
        - name: KAFKA_SERVER
          value: "172.16.16.150:9092"

# Create service
---
apiVersion: v1
kind: Service
metadata:
  namespace: kafka-consumer
  name: kafka-consumer-node-port
  labels:
    app: kafka-consumer
spec:
  type: NodePort
  selector:
    app: kafka-consumer
  ports:
    - protocol: TCP
      port: 8046
      targetPort: 8046
      name: port1