---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka-front
  labels:
    app: kafka-front

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kafka-front
  name: kafka-front
  labels:
    app: kafka-front
# Replica set
spec:
  revisionHistoryLimit: 5
  replicas: 1
  selector:
    matchLabels:
      app: kafka-front
# Pods
  template:
    metadata:
      labels:
        app: kafka-front
    spec:
      containers:
      - name: kafka-front
        image: registry.hub.docker.com/josegrelnx/kafka_front:latest
        ports:
          - containerPort: 8083
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 500Mi
            cpu: 500m
        env:
        - name: INPUT_TOPIC
          value: "input"
        - name: KAFKA_SERVER
          value: "172.16.16.150:9092"

# Create service
---
apiVersion: v1
kind: Service
metadata:
  namespace: kafka-front
  name: kafka-front-node-port
  labels:
    app: kafka-front
spec:
  type: NodePort
  selector:
    app: kafka-front
  ports:
    - protocol: TCP
      port: 8047
      targetPort: 8047
      name: port1